spring:
  application:
    name: "mlsh-chatrix"
  graphql:
    cors:
      allow-credentials: true
      allowed-origins:
        - "http://localhost:5173"
    graphiql:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${GOOGLE_AUTH_CLIENT_ID}"
            client-secret: "${GOOGLE_AUTH_CLIENT_SECRET}"
  data:
    mongodb:
      database: "mlsh-chatrix"
      uri: "${MONGODB_URI}"
      uuid-representation: standard
jwt:
  private:
    key: "classpath:app.key"
  public:
    key: "classpath:app.pub"